### ISSUE TITLE
Poor label usage in general

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/project2#11]
It seems like if only 10 percent of a groups labels were ever assigned that's not a great thing either.  It seems like that would mean that the scope of the project has changed, which could be a bad smell.

**Comment by duh102** [comment]
This one might be a bit difficult to quantify, since GitHub has a bunch of labels present by default, and label names can change over time (but we'd never know what labels used to be what), but here's some data you could work with:

Listing of labels observed in events:

``` SQL
select distinct label from event where action = 'labeled';
```

and count of them:

``` SQL
select count(distinct label) from event where action = 'labeled';
```

**Comment by meneal** [comment]
We can drop this one.  I agree that I'm not exactly sure how we would
quantify it.

**Comment by duh102** [comment]
I'll close this then, unless we find a good way to do it.
